"""U3-02: Active Rebalancer — generates orders to converge toward target weights.

Not just recalculating weights — generating ORDERS to close the gap.
Turnover-controlled, regime-aware, respects kill switches.
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

logger = logging.getLogger("alloc.rebalancer")


@dataclass
class RebalanceOrder:
    """An order generated by the rebalancer."""
    strategy: str
    instrument: str
    direction: str    # BUY or SELL
    notional: float
    reason: str       # "rebalance_underweight" or "rebalance_overweight"
    target_weight: float
    actual_weight: float

    def to_dict(self) -> dict:
        return {
            "strategy": self.strategy,
            "instrument": self.instrument,
            "direction": self.direction,
            "notional": round(self.notional, 2),
            "reason": self.reason,
            "target_pct": round(self.target_weight * 100, 1),
            "actual_pct": round(self.actual_weight * 100, 1),
        }


class ActiveRebalancer:
    """Generates rebalance orders to converge toward target allocation.

    Constraints:
      - Max rebalance per cycle: 5% of NAV
      - Min gap to trigger: 10%
      - Cooldown: 1h per strategy
      - PANIC: only reduce, never increase
      - STOPPED strategies: never rebalance toward them

    Usage:
        rebalancer = ActiveRebalancer()
        orders = rebalancer.compute_rebalance(
            target_weights={"fx_carry": 0.25, ...},
            actual_weights={"fx_carry": 0.05, ...},
            nav_total=45000,
            regime="TREND_STRONG",
            stopped_strategies=["bad_strat"],
        )
    """

    def __init__(
        self,
        max_rebalance_pct: float = 0.05,   # 5% of NAV per cycle
        min_gap_to_trigger: float = 0.10,   # 10% gap minimum
        cooldown_hours: float = 1.0,
    ):
        self._max_rebalance = max_rebalance_pct
        self._min_gap = min_gap_to_trigger
        self._cooldown = timedelta(hours=cooldown_hours)
        self._last_rebalance: Dict[str, datetime] = {}

    def compute_rebalance(
        self,
        target_weights: Dict[str, float],
        actual_weights: Dict[str, float],
        nav_total: float,
        regime: str = "UNKNOWN",
        stopped_strategies: List[str] = None,
        instrument_map: Dict[str, str] = None,
    ) -> List[RebalanceOrder]:
        """Compute rebalance orders."""
        stopped = set(stopped_strategies or [])
        instrument_map = instrument_map or {}
        orders = []
        now = datetime.now()
        total_rebalance = 0.0
        max_rebalance_usd = nav_total * self._max_rebalance

        for strat, target in target_weights.items():
            actual = actual_weights.get(strat, 0)
            gap = target - actual

            # Skip if gap too small
            if abs(gap) < self._min_gap:
                continue

            # Skip stopped strategies
            if strat in stopped:
                continue

            # Cooldown check
            last = self._last_rebalance.get(strat)
            if last and (now - last) < self._cooldown:
                continue

            # PANIC: only reduce, never increase
            if regime == "PANIC" and gap > 0:
                continue

            # UNKNOWN: rebalance at 50% of gap only
            if regime == "UNKNOWN":
                gap *= 0.5

            # Compute order
            notional = abs(gap) * nav_total
            notional = min(notional, max_rebalance_usd - total_rebalance)

            if notional < 50:  # Below min size
                continue

            direction = "BUY" if gap > 0 else "SELL"
            instrument = instrument_map.get(strat, strat)

            orders.append(RebalanceOrder(
                strategy=strat,
                instrument=instrument,
                direction=direction,
                notional=notional,
                reason=f"rebalance_{'underweight' if gap > 0 else 'overweight'}",
                target_weight=target,
                actual_weight=actual,
            ))

            total_rebalance += notional
            self._last_rebalance[strat] = now

            if total_rebalance >= max_rebalance_usd:
                break

        logger.info(
            "Rebalancer: %d orders, $%.0f total (max $%.0f)",
            len(orders), total_rebalance, max_rebalance_usd,
        )

        return orders
